[tool.poetry]
name = "acme-appstub"
version = "0.1.0"
description = ""
authors = ["Matthew Reschke <mail@mreschke.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
uvicore = {path = "../uvicore", develop = true}
aiomysql = "^0.0.20"
aiosqlite = "^0.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
