[tool.poetry]
name = "acme-appstub"
version = "0.1.0"
description = ""
authors = ["Artisan Smith <smith@example.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
uvicore = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
